### ISSUE TITLE
Error al crear

### ISSUE THREAD

**Issue by KatuGT** [JulianMartin98/rollingMarketFront#1]
Puse un precio mayor al permitido según las validaciones en el back pero aun así me aparecio el mensaje de "creado exitosamente" cuando en realidad no se creo  ya que en "network" se visualiza el error

![image](https://github.com/JulianMartin98/rollingMarketFront/assets/38865485/338fbe10-334f-411d-8981-690d4f8a1948)

**Comment by alamodeg** [comment]
Buenas @KatuGT , implementamos los siguientes cambios para corregir el bug, aquí un pequeño changelog:

### Solucionado

- Se agregaron validadores para que la edición de productos tenga coherencia con el modelo del backend.
- Se agregaron alertas específicas para indicar el éxito o fracaso al crear y editar productos.
- Corrección de links en el archivo README

### Eliminado
- Se eliminaron los mensajes genéricos del frontend al crear y editar productos.
